// <auto-generated />
using System;
using MESManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MESManager.Infrastructure.Migrations
{
    [DbContext(typeof(MesManagerDbContext))]
    [Migration("20260420100656_AddAllegatiPreventivi")]
    partial class AddAllegatiPreventivi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MESManager.Domain.Entities.AllegatoArticolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Archivio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodiceArticolo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataImportazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("DimensioneBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Estensione")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("IdArchivio")
                        .HasColumnType("int");

                    b.Property<int?>("IdGanttOriginale")
                        .HasColumnType("int");

                    b.Property<bool>("ImportatoDaGantt")
                        .HasColumnType("bit");

                    b.Property<string>("NomeFile")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priorita")
                        .HasColumnType("int");

                    b.Property<string>("TipoFile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CodiceArticolo");

                    b.HasIndex("IdGanttOriginale");

                    b.HasIndex("Archivio", "IdArchivio");

                    b.ToTable("AllegatiArticoli");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.AllegatoPreventivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Dati")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("DimensioneBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PreventivoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PreventivoId");

                    b.ToTable("AllegatiPreventivi");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allegato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Altezza")
                        .HasColumnType("int");

                    b.Property<string>("ArmataL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Assemblata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciclo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceAnime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceArticolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceCassa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataImportazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModificaRecord")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaModificaLocale")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescrizioneArticolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Figure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdArticolo")
                        .HasColumnType("int");

                    b.Property<int?>("Imballo")
                        .HasColumnType("int");

                    b.Property<int?>("Larghezza")
                        .HasColumnType("int");

                    b.Property<string>("MacchineSuDisponibili")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maschere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModificatoLocalmente")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroPiani")
                        .HasColumnType("int");

                    b.Property<string>("Peso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Profondita")
                        .HasColumnType("int");

                    b.Property<int?>("QuantitaPiano")
                        .HasColumnType("int");

                    b.Property<string>("Sabbia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TogliereSparo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrasmettiTutto")
                        .HasColumnType("bit");

                    b.Property<string>("Ubicazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitaMisura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModificaRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteUltimaModificaLocale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vernice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.AnomaliaStandardManutenzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attiva")
                        .HasColumnType("bit");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnomalieStandardManutenzione");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Articolo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("ClasseLavorazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroFigure")
                        .HasColumnType("int");

                    b.Property<decimal>("Prezzo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TempoCiclo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("Articoli");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.CalendarioLavoro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Domenica")
                        .HasColumnType("bit");

                    b.Property<bool>("Giovedi")
                        .HasColumnType("bit");

                    b.Property<bool>("Lunedi")
                        .HasColumnType("bit");

                    b.Property<bool>("Martedi")
                        .HasColumnType("bit");

                    b.Property<bool>("Mercoledi")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("OraFine")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OraInizio")
                        .HasColumnType("time");

                    b.Property<bool>("Sabato")
                        .HasColumnType("bit");

                    b.Property<bool>("Venerdi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CalendarioLavoro");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Commessa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticoloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Bloccata")
                        .HasColumnType("bit");

                    b.Property<string>("ClasseLavorazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataCambioStatoProgramma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConsegna")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinePrevisione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFineProduzione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInizioPrevisione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInizioProduzione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalOrdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalOrdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroMacchina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrdineSequenza")
                        .HasColumnType("int");

                    b.Property<string>("OurReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priorita")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantitaRichiesta")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RiferimentoOrdineCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SaleOrdId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SetupStimatoMinuti")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int>("StatoProgramma")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("UoM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VincoloDataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VincoloDataInizio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticoloId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codice");

                    b.HasIndex("StatoProgramma");

                    b.ToTable("Commesse");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ConfigurazionePLC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeParametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.ToTable("ConfigurazioniPLC");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.EventoPLC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.ToTable("EventiPLC");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Festivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Anno")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ricorrente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Ricorrente");

                    b.ToTable("Festivi");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ImpostazioniGantt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AbilitaTempoAttrezzaggio")
                        .HasColumnType("bit");

                    b.Property<int>("BufferInizioProduzioneMinuti")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<int>("TempoAttrezzaggioMinutiDefault")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImpostazioniGantt");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ImpostazioniProduzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GiorniLavorativiSettimanali")
                        .HasColumnType("int");

                    b.Property<int>("OreLavorativeGiornaliere")
                        .HasColumnType("int");

                    b.Property<int>("TempoSetupMinuti")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ImpostazioniProduzione");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.LogEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Azione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdEntita")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Utente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorePrecedenteJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoreSuccessivoJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogEventi");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.LogSyncEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Aggiornati")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<int>("Errori")
                        .HasColumnType("int");

                    b.Property<string>("FileBackupPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ignorati")
                        .HasColumnType("int");

                    b.Property<string>("MessaggioErrore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nuovi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LogSync");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Macchina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AttivaInGantt")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IndirizzoFtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndirizzoPLC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdineVisualizazione")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codice");

                    b.ToTable("Macchine");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Manutenzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataEsecuzione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.ToTable("Manutenzioni");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneAttivita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attiva")
                        .HasColumnType("bit");

                    b.Property<int?>("CicliSogliaPLC")
                        .HasColumnType("int");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<int>("TipoFrequenza")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoFrequenza");

                    b.ToTable("ManutenzioneAttivita");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneCassaAllegato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("DimensioneBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Estensione")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SchedaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoFile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Documento");

                    b.HasKey("Id");

                    b.HasIndex("SchedaId");

                    b.ToTable("ManutenzioneCasseAllegati", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneCassaAttivita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attiva")
                        .HasColumnType("bit");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Attiva");

                    b.ToTable("ManutenzioneCassaAttivita", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneCassaRiga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttivitaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Esito")
                        .HasColumnType("int");

                    b.Property<Guid>("SchedaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttivitaId");

                    b.HasIndex("SchedaId");

                    b.ToTable("ManutenzioneCasseRighe", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneCassaScheda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodiceCassa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CodiceRiferimento")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataChiusura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEsecuzione")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeOperatore")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatoreId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProblematicheJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodiceCassa");

                    b.HasIndex("DataEsecuzione");

                    b.ToTable("ManutenzioneCasseSchede", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneRiga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttivitaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CicloMacchinaAlEsecuzione")
                        .HasColumnType("int");

                    b.Property<string>("Commento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Esito")
                        .HasColumnType("int");

                    b.Property<string>("FotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SchedaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttivitaId");

                    b.HasIndex("SchedaId");

                    b.ToTable("ManutenzioneRighe");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneScheda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataChiusura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEsecuzione")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeOperatore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatoreId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int>("TipoFrequenza")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataEsecuzione");

                    b.HasIndex("MacchinaId");

                    b.ToTable("ManutenzioneSchede");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Operatore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAssunzione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLicenziamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroOperatore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Operatori");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCRealtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BarcodeLavorazione")
                        .HasColumnType("int");

                    b.Property<int>("CicliFatti")
                        .HasColumnType("int");

                    b.Property<int>("CicliScarti")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUltimoAggiornamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Figure")
                        .HasColumnType("int");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroOperatore")
                        .HasColumnType("int");

                    b.Property<Guid?>("OperatoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantitaDaProdurre")
                        .HasColumnType("int");

                    b.Property<bool>("QuantitaRaggiunta")
                        .HasColumnType("bit");

                    b.Property<string>("StatoMacchina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempoMedio")
                        .HasColumnType("int");

                    b.Property<int>("TempoMedioRilevato")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.HasIndex("OperatoreId");

                    b.ToTable("PLCRealtime");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCStorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroOperatore")
                        .HasColumnType("int");

                    b.Property<Guid?>("OperatoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatoMacchina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.HasIndex("OperatoreId");

                    b.ToTable("PLCStorico");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ParametroRicetta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodiceParametro")
                        .HasColumnType("int");

                    b.Property<int?>("Indirizzo")
                        .HasColumnType("int");

                    b.Property<string>("NomeParametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RicettaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitaMisura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RicettaId");

                    b.ToTable("ParametriRicetta");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PlcServiceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnableEvents")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableRealtime")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableStorico")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastErrorTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachinesConfigured")
                        .HasColumnType("int");

                    b.Property<int>("MachinesConnected")
                        .HasColumnType("int");

                    b.Property<int>("PollingIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ServiceStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalErrorCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalSyncCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlcServiceStatus");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PlcSyncLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MacchinaNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("MacchinaId");

                    b.HasIndex("Timestamp");

                    b.ToTable("PlcSyncLogs");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PreferenzaUtente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chiave")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValoreJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Chiave")
                        .IsUnique();

                    b.ToTable("PreferenzeUtente");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Preventivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalcCostoAnima")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("CalcPrezzoVendita")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("CalcVerniciaturaTot")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodiceArticolo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CommessaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostoAttrezzatura")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CostoVerniceKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailDestinatario")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("EmailInviatoIl")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EuroOraImballaggio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EuroOraIncollaggio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EuroOraSabbia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EuroOraVerniciatura")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Figure")
                        .HasColumnType("int");

                    b.Property<int>("ImballaggioPzOra")
                        .HasColumnType("int");

                    b.Property<bool>("ImballaggioRichiesto")
                        .HasColumnType("bit");

                    b.Property<int>("IncollaggioPzOra")
                        .HasColumnType("int");

                    b.Property<bool>("IncollaggioRichiesto")
                        .HasColumnType("bit");

                    b.Property<int>("Lotto")
                        .HasColumnType("int");

                    b.Property<int?>("Lotto2")
                        .HasColumnType("int");

                    b.Property<int?>("Lotto3")
                        .HasColumnType("int");

                    b.Property<int?>("Lotto4")
                        .HasColumnType("int");

                    b.Property<decimal>("Margine1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Margine2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Margine3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Margine4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoteCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteInterne")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NumeroPreventivo")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentualeVernice")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PesoAnima")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("PrezzoSabbiaKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("SabbiaSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Sconto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("SpariOrari")
                        .HasColumnType("int");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("InAttesa");

                    b.Property<Guid?>("TipoSabbiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TipoVerniceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerniceSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VerniciaturaPzOra")
                        .HasColumnType("int");

                    b.Property<bool>("VerniciaturaRichiesta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Cliente");

                    b.HasIndex("DataCreazione");

                    b.HasIndex("TipoSabbiaId");

                    b.HasIndex("TipoVerniceId");

                    b.ToTable("Preventivi", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PreventivoRevisione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataRevisione")
                        .HasColumnType("datetime2");

                    b.Property<string>("DtoJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteRevisione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumeroRevisione")
                        .HasColumnType("int");

                    b.Property<Guid>("PreventivoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PreventivoId");

                    b.ToTable("PreventivoRevisioni", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PreventivoTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParametriJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PreventivoTemplates", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PreventivoTipoSabbia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("EuroOra")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Famiglia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("SpariDefault")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PreventivoTipiSabbia", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PreventivoTipoVernice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Famiglia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentualeApplicazione")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrezzoKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("PreventivoTipiVernice", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Ricetta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticoloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimoAggiornamento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticoloId")
                        .IsUnique();

                    b.ToTable("Ricette");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.StoricoProgrammazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommessaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatoNuovo")
                        .HasColumnType("int");

                    b.Property<int?>("StatoPrecedente")
                        .HasColumnType("int");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommessaId");

                    b.HasIndex("DataModifica");

                    b.ToTable("StoricoProgrammazione");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.SyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UltimaSyncRiuscita")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Modulo")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.TechnicalIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocsReferencePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("DocsUpdated")
                        .HasColumnType("bit");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<bool>("ExportedToAI")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExportedToAIAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAutoCapture")
                        .HasColumnType("bit");

                    b.Property<string>("Logs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReproSteps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RulesLearned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Area");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Environment");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.ToTable("TechnicalIssues");
                });

            modelBuilder.Entity("MESManager.Infrastructure.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Colore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MESManager.Domain.Entities.AllegatoPreventivo", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Preventivo", "Preventivo")
                        .WithMany()
                        .HasForeignKey("PreventivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preventivo");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Commessa", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Articolo", "Articolo")
                        .WithMany("Commesse")
                        .HasForeignKey("ArticoloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESManager.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Commesse")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Articolo");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ConfigurazionePLC", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("ConfigurazioniPLC")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.EventoPLC", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("EventiPLC")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Manutenzione", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("Manutenzioni")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneCassaAllegato", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.ManutenzioneCassaScheda", "Scheda")
                        .WithMany()
                        .HasForeignKey("SchedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scheda");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneCassaRiga", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.ManutenzioneCassaAttivita", "Attivita")
                        .WithMany("Righe")
                        .HasForeignKey("AttivitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESManager.Domain.Entities.ManutenzioneCassaScheda", "Scheda")
                        .WithMany("Righe")
                        .HasForeignKey("SchedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attivita");

                    b.Navigation("Scheda");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneRiga", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.ManutenzioneAttivita", "Attivita")
                        .WithMany("Righe")
                        .HasForeignKey("AttivitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESManager.Domain.Entities.ManutenzioneScheda", "Scheda")
                        .WithMany("Righe")
                        .HasForeignKey("SchedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attivita");

                    b.Navigation("Scheda");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneScheda", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("SchedeManutenzione")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCRealtime", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany()
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESManager.Domain.Entities.Operatore", "Operatore")
                        .WithMany()
                        .HasForeignKey("OperatoreId");

                    b.Navigation("Macchina");

                    b.Navigation("Operatore");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCStorico", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany()
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESManager.Domain.Entities.Operatore", "Operatore")
                        .WithMany()
                        .HasForeignKey("OperatoreId");

                    b.Navigation("Macchina");

                    b.Navigation("Operatore");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ParametroRicetta", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Ricetta", "Ricetta")
                        .WithMany("Parametri")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PlcSyncLog", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany()
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Preventivo", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.PreventivoTipoSabbia", "TipoSabbia")
                        .WithMany()
                        .HasForeignKey("TipoSabbiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MESManager.Domain.Entities.PreventivoTipoVernice", "TipoVernice")
                        .WithMany()
                        .HasForeignKey("TipoVerniceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TipoSabbia");

                    b.Navigation("TipoVernice");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PreventivoRevisione", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Preventivo", null)
                        .WithMany()
                        .HasForeignKey("PreventivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Ricetta", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Articolo", "Articolo")
                        .WithOne("Ricetta")
                        .HasForeignKey("MESManager.Domain.Entities.Ricetta", "ArticoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articolo");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.StoricoProgrammazione", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Commessa", "Commessa")
                        .WithMany("StoricoProgrammazione")
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commessa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MESManager.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MESManager.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESManager.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MESManager.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Articolo", b =>
                {
                    b.Navigation("Commesse");

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Commesse");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Commessa", b =>
                {
                    b.Navigation("StoricoProgrammazione");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Macchina", b =>
                {
                    b.Navigation("ConfigurazioniPLC");

                    b.Navigation("EventiPLC");

                    b.Navigation("Manutenzioni");

                    b.Navigation("SchedeManutenzione");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneAttivita", b =>
                {
                    b.Navigation("Righe");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneCassaAttivita", b =>
                {
                    b.Navigation("Righe");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneCassaScheda", b =>
                {
                    b.Navigation("Righe");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ManutenzioneScheda", b =>
                {
                    b.Navigation("Righe");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Ricetta", b =>
                {
                    b.Navigation("Parametri");
                });
#pragma warning restore 612, 618
        }
    }
}
