// <auto-generated />
using System;
using MESManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MESManager.Infrastructure.Migrations
{
    [DbContext(typeof(MesManagerDbContext))]
    partial class MesManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MESManager.Domain.Entities.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allegato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Altezza")
                        .HasColumnType("int");

                    b.Property<string>("Ciclo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceAnime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceArticolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceCassa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataImportazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModificaRecord")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescrizioneArticolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdArticolo")
                        .HasColumnType("int");

                    b.Property<int?>("Imballo")
                        .HasColumnType("int");

                    b.Property<int?>("Larghezza")
                        .HasColumnType("int");

                    b.Property<string>("MacchineSuDisponibili")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Profondita")
                        .HasColumnType("int");

                    b.Property<bool>("TrasmettiTutto")
                        .HasColumnType("bit");

                    b.Property<string>("Ubicazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitaMisura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UtenteModificaRecord")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Articolo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimestampSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("Articoli");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Commessa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticoloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DataConsegna")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("QuantitaRichiesta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RiferimentoOrdineCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticoloId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codice");

                    b.ToTable("Commesse");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ConfigurazionePLC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeParametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.ToTable("ConfigurazioniPLC");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.EventoPLC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.ToTable("EventiPLC");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.LogEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Azione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdEntita")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Utente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorePrecedenteJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoreSuccessivoJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogEventi");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.LogSyncEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Aggiornati")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<int>("Errori")
                        .HasColumnType("int");

                    b.Property<string>("FileBackupPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ignorati")
                        .HasColumnType("int");

                    b.Property<string>("MessaggioErrore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nuovi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LogSync");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Macchina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codice");

                    b.ToTable("Macchine");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Manutenzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataEsecuzione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.ToTable("Manutenzioni");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Operatore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAssunzione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLicenziamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroOperatore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Operatori");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCRealtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BarcodeLavorazione")
                        .HasColumnType("int");

                    b.Property<int>("CicliFatti")
                        .HasColumnType("int");

                    b.Property<int>("CicliScarti")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUltimoAggiornamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Figure")
                        .HasColumnType("int");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroOperatore")
                        .HasColumnType("int");

                    b.Property<Guid?>("OperatoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantitaDaProdurre")
                        .HasColumnType("int");

                    b.Property<bool>("QuantitaRaggiunta")
                        .HasColumnType("bit");

                    b.Property<string>("StatoMacchina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempoMedio")
                        .HasColumnType("int");

                    b.Property<int>("TempoMedioRilevato")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.HasIndex("OperatoreId");

                    b.ToTable("PLCRealtime");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCStorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroOperatore")
                        .HasColumnType("int");

                    b.Property<Guid?>("OperatoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatoMacchina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.HasIndex("OperatoreId");

                    b.ToTable("PLCStorico");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ParametroRicetta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeParametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RicettaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitaMisura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RicettaId");

                    b.ToTable("ParametriRicetta");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Ricetta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticoloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArticoloId")
                        .IsUnique();

                    b.ToTable("Ricette");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.SyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UltimaSyncRiuscita")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Modulo")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Commessa", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Articolo", "Articolo")
                        .WithMany("Commesse")
                        .HasForeignKey("ArticoloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESManager.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Commesse")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Articolo");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ConfigurazionePLC", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("ConfigurazioniPLC")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.EventoPLC", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("EventiPLC")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Manutenzione", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("Manutenzioni")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCRealtime", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany()
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESManager.Domain.Entities.Operatore", "Operatore")
                        .WithMany()
                        .HasForeignKey("OperatoreId");

                    b.Navigation("Macchina");

                    b.Navigation("Operatore");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCStorico", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany()
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESManager.Domain.Entities.Operatore", "Operatore")
                        .WithMany()
                        .HasForeignKey("OperatoreId");

                    b.Navigation("Macchina");

                    b.Navigation("Operatore");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ParametroRicetta", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Ricetta", "Ricetta")
                        .WithMany("Parametri")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Ricetta", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Articolo", "Articolo")
                        .WithOne("Ricetta")
                        .HasForeignKey("MESManager.Domain.Entities.Ricetta", "ArticoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articolo");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Articolo", b =>
                {
                    b.Navigation("Commesse");

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Commesse");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Macchina", b =>
                {
                    b.Navigation("ConfigurazioniPLC");

                    b.Navigation("EventiPLC");

                    b.Navigation("Manutenzioni");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Ricetta", b =>
                {
                    b.Navigation("Parametri");
                });
#pragma warning restore 612, 618
        }
    }
}
