// <auto-generated />
using System;
using MESManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MESManager.Infrastructure.Migrations
{
    [DbContext(typeof(MesManagerDbContext))]
    partial class MesManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MESManager.Domain.Entities.AllegatoArticolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Archivio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodiceArticolo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataImportazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("DimensioneBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Estensione")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("IdArchivio")
                        .HasColumnType("int");

                    b.Property<int?>("IdGanttOriginale")
                        .HasColumnType("int");

                    b.Property<bool>("ImportatoDaGantt")
                        .HasColumnType("bit");

                    b.Property<string>("NomeFile")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priorita")
                        .HasColumnType("int");

                    b.Property<string>("TipoFile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CodiceArticolo");

                    b.HasIndex("IdGanttOriginale");

                    b.HasIndex("Archivio", "IdArchivio");

                    b.ToTable("AllegatiArticoli");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allegato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Altezza")
                        .HasColumnType("int");

                    b.Property<string>("ArmataL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Assemblata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciclo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceAnime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceArticolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceCassa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataImportazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModificaRecord")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaModificaLocale")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescrizioneArticolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Figure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdArticolo")
                        .HasColumnType("int");

                    b.Property<int?>("Imballo")
                        .HasColumnType("int");

                    b.Property<int?>("Larghezza")
                        .HasColumnType("int");

                    b.Property<string>("MacchineSuDisponibili")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maschere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModificatoLocalmente")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroPiani")
                        .HasColumnType("int");

                    b.Property<string>("Peso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Profondita")
                        .HasColumnType("int");

                    b.Property<int?>("QuantitaPiano")
                        .HasColumnType("int");

                    b.Property<string>("Sabbia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TogliereSparo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrasmettiTutto")
                        .HasColumnType("bit");

                    b.Property<string>("Ubicazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitaMisura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteModificaRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteUltimaModificaLocale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vernice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Articolo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("ClasseLavorazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroFigure")
                        .HasColumnType("int");

                    b.Property<decimal>("Prezzo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TempoCiclo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("Articoli");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.CalendarioLavoro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Domenica")
                        .HasColumnType("bit");

                    b.Property<bool>("Giovedi")
                        .HasColumnType("bit");

                    b.Property<bool>("Lunedi")
                        .HasColumnType("bit");

                    b.Property<bool>("Martedi")
                        .HasColumnType("bit");

                    b.Property<bool>("Mercoledi")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("OraFine")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OraInizio")
                        .HasColumnType("time");

                    b.Property<bool>("Sabato")
                        .HasColumnType("bit");

                    b.Property<bool>("Venerdi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CalendarioLavoro");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Commessa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticoloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Bloccata")
                        .HasColumnType("bit");

                    b.Property<string>("ClasseLavorazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataCambioStatoProgramma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConsegna")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinePrevisione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFineProduzione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInizioPrevisione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInizioProduzione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalOrdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalOrdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroMacchina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdineSequenza")
                        .HasColumnType("int");

                    b.Property<string>("OurReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priorita")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantitaRichiesta")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RiferimentoOrdineCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SaleOrdId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SetupStimatoMinuti")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int>("StatoProgramma")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("UoM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VincoloDataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VincoloDataInizio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticoloId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codice");

                    b.HasIndex("StatoProgramma");

                    b.ToTable("Commesse");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ConfigurazionePLC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeParametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.ToTable("ConfigurazioniPLC");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.EventoPLC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.ToTable("EventiPLC");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Festivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Anno")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ricorrente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Ricorrente");

                    b.ToTable("Festivi");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ImpostazioniGantt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AbilitaTempoAttrezzaggio")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<int>("TempoAttrezzaggioMinutiDefault")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImpostazioniGantt");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ImpostazioniProduzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GiorniLavorativiSettimanali")
                        .HasColumnType("int");

                    b.Property<int>("OreLavorativeGiornaliere")
                        .HasColumnType("int");

                    b.Property<int>("TempoSetupMinuti")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ImpostazioniProduzione");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.LogEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Azione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdEntita")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Utente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorePrecedenteJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoreSuccessivoJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogEventi");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.LogSyncEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Aggiornati")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<int>("Errori")
                        .HasColumnType("int");

                    b.Property<string>("FileBackupPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ignorati")
                        .HasColumnType("int");

                    b.Property<string>("MessaggioErrore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nuovi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LogSync");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Macchina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AttivaInGantt")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IndirizzoPLC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdineVisualizazione")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codice");

                    b.ToTable("Macchine");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Manutenzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataEsecuzione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.ToTable("Manutenzioni");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Operatore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAssunzione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLicenziamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroOperatore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Operatori");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCRealtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BarcodeLavorazione")
                        .HasColumnType("int");

                    b.Property<int>("CicliFatti")
                        .HasColumnType("int");

                    b.Property<int>("CicliScarti")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUltimoAggiornamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Figure")
                        .HasColumnType("int");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroOperatore")
                        .HasColumnType("int");

                    b.Property<Guid?>("OperatoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantitaDaProdurre")
                        .HasColumnType("int");

                    b.Property<bool>("QuantitaRaggiunta")
                        .HasColumnType("bit");

                    b.Property<string>("StatoMacchina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempoMedio")
                        .HasColumnType("int");

                    b.Property<int>("TempoMedioRilevato")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.HasIndex("OperatoreId");

                    b.ToTable("PLCRealtime");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCStorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroOperatore")
                        .HasColumnType("int");

                    b.Property<Guid?>("OperatoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatoMacchina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MacchinaId");

                    b.HasIndex("OperatoreId");

                    b.ToTable("PLCStorico");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ParametroRicetta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeParametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RicettaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitaMisura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RicettaId");

                    b.ToTable("ParametriRicetta");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PlcServiceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnableEvents")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableRealtime")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableStorico")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastErrorTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachinesConfigured")
                        .HasColumnType("int");

                    b.Property<int>("MachinesConnected")
                        .HasColumnType("int");

                    b.Property<int>("PollingIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ServiceStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalErrorCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalSyncCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlcServiceStatus");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PlcSyncLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("MacchinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MacchinaNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("MacchinaId");

                    b.HasIndex("Timestamp");

                    b.ToTable("PlcSyncLogs");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PreferenzaUtente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chiave")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UtenteAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValoreJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UtenteAppId", "Chiave")
                        .IsUnique();

                    b.ToTable("PreferenzeUtente");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("ValidFrom");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PriceListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("PriceListId", "Code")
                        .IsUnique();

                    b.ToTable("PriceListItems");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PriceListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PriceListVersionSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TaxableAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VatTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Date");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PriceListId");

                    b.HasIndex("Status");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.QuoteAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteAttachments");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.QuoteRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PriceListItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RowTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RowType")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VatPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("PriceListItemId");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteRows");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Ricetta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticoloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArticoloId")
                        .IsUnique();

                    b.ToTable("Ricette");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.StoricoProgrammazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommessaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatoNuovo")
                        .HasColumnType("int");

                    b.Property<int?>("StatoPrecedente")
                        .HasColumnType("int");

                    b.Property<string>("UtenteModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommessaId");

                    b.HasIndex("DataModifica");

                    b.ToTable("StoricoProgrammazione");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.SyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UltimaSyncRiuscita")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Modulo")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.TechnicalIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocsReferencePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("DocsUpdated")
                        .HasColumnType("bit");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<string>("Logs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReproSteps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RulesLearned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Area");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Environment");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.ToTable("TechnicalIssues");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.UtenteApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Colore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaModifica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("UtentiApp");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Commessa", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Articolo", "Articolo")
                        .WithMany("Commesse")
                        .HasForeignKey("ArticoloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESManager.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Commesse")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Articolo");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ConfigurazionePLC", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("ConfigurazioniPLC")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.EventoPLC", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("EventiPLC")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Manutenzione", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany("Manutenzioni")
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCRealtime", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany()
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESManager.Domain.Entities.Operatore", "Operatore")
                        .WithMany()
                        .HasForeignKey("OperatoreId");

                    b.Navigation("Macchina");

                    b.Navigation("Operatore");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PLCStorico", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany()
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESManager.Domain.Entities.Operatore", "Operatore")
                        .WithMany()
                        .HasForeignKey("OperatoreId");

                    b.Navigation("Macchina");

                    b.Navigation("Operatore");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.ParametroRicetta", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Ricetta", "Ricetta")
                        .WithMany("Parametri")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PlcSyncLog", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Macchina", "Macchina")
                        .WithMany()
                        .HasForeignKey("MacchinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Macchina");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PreferenzaUtente", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.UtenteApp", "UtenteApp")
                        .WithMany("Preferenze")
                        .HasForeignKey("UtenteAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UtenteApp");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PriceListItem", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.PriceList", "PriceList")
                        .WithMany("Items")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Quote", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MESManager.Domain.Entities.PriceList", "PriceList")
                        .WithMany("Quotes")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.QuoteAttachment", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Quote", "Quote")
                        .WithMany("Attachments")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.QuoteRow", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.PriceListItem", "PriceListItem")
                        .WithMany("QuoteRows")
                        .HasForeignKey("PriceListItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MESManager.Domain.Entities.Quote", "Quote")
                        .WithMany("Rows")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceListItem");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Ricetta", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Articolo", "Articolo")
                        .WithOne("Ricetta")
                        .HasForeignKey("MESManager.Domain.Entities.Ricetta", "ArticoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articolo");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.StoricoProgrammazione", b =>
                {
                    b.HasOne("MESManager.Domain.Entities.Commessa", "Commessa")
                        .WithMany("StoricoProgrammazione")
                        .HasForeignKey("CommessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commessa");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Articolo", b =>
                {
                    b.Navigation("Commesse");

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Commesse");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Commessa", b =>
                {
                    b.Navigation("StoricoProgrammazione");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Macchina", b =>
                {
                    b.Navigation("ConfigurazioniPLC");

                    b.Navigation("EventiPLC");

                    b.Navigation("Manutenzioni");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PriceList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.PriceListItem", b =>
                {
                    b.Navigation("QuoteRows");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.Ricetta", b =>
                {
                    b.Navigation("Parametri");
                });

            modelBuilder.Entity("MESManager.Domain.Entities.UtenteApp", b =>
                {
                    b.Navigation("Preferenze");
                });
#pragma warning restore 612, 618
        }
    }
}
